name: Deploy Java to EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy Java Application to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy JAR to EC2
        uses: easingthemes/ssh-deploy@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
        with:
          source: target/myapp.jar
          target: /home/ubuntu/myapp.jar

      - name: Execute remote commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            java -jar /home/ubuntu/myapp.jar
